### ISSUE TITLE
Game of Madness - Courtney LAB

### ISSUE THREAD

**Issue by Courtney-Seitz** [ga-wdi-exercises/game_of_thrones#10]
https://github.com/CourtneySeitz/Game_of_Rails

Comfort-level: 3.5
Completeness: 3

I missed a day and had to catch up on time, but then spent too much on styling css. I managed to get the Houses working, but then in trying to incorporate the nesting for the Characters, and getting stuck on a few small errors for too long...well, I ran out of precious time to accomplish all of the requirements.  Overall, this was super fun to make. Need to focus on HW now.

**Comment by nayana487** [comment]
Looks like you were trying to migrate duplicate columns, which is why you probably weren't able to see your site in the browser. If you get rid of the add column migration file, you should be able to see it.  Other than that, it looks like you got full CRUD functionality on the house model. Go ahead and try this out with the character model now.
